### ISSUE TITLE
Which Warcraft games do you play/mod?

### ISSUE THREAD

**Issue by mollikka** [silvenon/ama#6]

**Comment by silvenon** [comment]
I have never done a map from start to finish, but I have collaborated on:

* Alien vs. Predator
* some FPS with night vision and stuff (which is pretty WTF for Warcraft)
* some short cinematics
* a story written by my friend about a necromancer, which was way too advanced for me to build :sweat_smile: 

I've never been very successful at modding Warcraft, but it was crazy and pointless anyway, the engine and graphics were 10 years old and it became a contest who can hack Warcraft the most :smiley:
