### ISSUE TITLE
What tools do you use on a daily basis?

### ISSUE THREAD

**Issue by sindresorhus** [silvenon/ama#9]

**Comment by silvenon** [comment]
* [Git](http://git-scm.com/)
* [Atom](https://atom.io/)
* [gulp](http://gulpjs.com/)
* [Sass](http://sass-lang.com/)
* [PostCSS](https://github.com/postcss/postcss)
* [Autoprefixer](https://github.com/postcss/autoprefixer)
* [imagemin](https://github.com/imagemin/imagemin)
* [browserify](http://browserify.org/)
* [React](https://facebook.github.io/react/)
* [ESLint](http://eslint.org/)
* [BrowserSync](http://www.browsersync.io/)
* [Cross Browser Testing](https://crossbrowsertesting.com/)
* …
